#include    <sgl.h>

#include    "sprite.h"
#include 	"overwatch.txr" //generated by 3DEditor

Sprite sprites[2] = {
	{SPR_TYPE_SINGLE, "yospos", {toFIXED(0.0), toFIXED(0.0), toFIXED(169), toFIXED(1.0)}, DEGtoANG(0.0), 0, 0, 0, NULL, NULL, 0, {0, 0}},
	{SPR_TYPE_SINGLE, "skull", {toFIXED(80.0), toFIXED(0.0), toFIXED(169), toFIXED(1.0)}, DEGtoANG(0.0), 0, 0, 0, NULL, NULL, 0, {0, 0}},
};
